stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/processed/processed.py
    deps:
    - data/raw
    - src/processed/processed.py
    outs:
    - data/interim


  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
    - data/interim
    - src/features/build_features.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed

  model_building:
    cmd: python src/model/train_model.py
    deps:
    - data/processed
    - src/model/train_model.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/predict_model.py
    deps:
    - models/model.pkl
    - src/model/predict_model.py
    metrics:
    - reports/metrics.json
